### ISSUE TITLE
Sumário

### ISSUE THREAD

**Issue by tarcisiofischer** [tarcisiofischer/livrocpp#1]
Conforme sugerido por algumas pessoas no grupo, segue a sugestão / esboço inicial de sumário que saiu da minha cabeça. Provavelmente esqueci algum tópico e/ou coloquei em lugar inadequado. Peço ajuda para definir um sumário inicial.

```
## Sumário

- [Capítulo 1](./capitulo1.md): Olá mundo!
- [Capítulo 2](./capitulo2.md): Sintaxe básica
    - 2.1: Variáveis
    - 2.2: Estruturas de controle
    - 2.3: Funções
    - 2.4: Tipos definidos pelo usuário
    - 2.5: Ponteiros, referências e const
    - 2.6: Funções lambda
- [Capítulo 3](./capitulo3.md): Introdução à biblioteca padrão do C++
    - 3.1: vector
    - 3.2: map
    - 3.3: array
- [Capítulo 4](./capitulo4.md): Trabalhando com projetos
    - 4.1: Processo de compilação
    - 4.2: Trabalhando com vários arquivos
    - 4.3: Gerenciamento de pacotes
- [Capítulo 5](./capitulo5.md): Programação orientada a objetos
    - 5.1: Classes e objetos
    - 5.2: Herança e polimorfismo
    - 5.3: Composição vs herança
    - 5.4: Tratamento de erros e exceções
    - 5.5: Sobrecarga de operadores
    - 5.6: Gerenciamento de recursos e RAII
- [Capítulo 6](./capitulo6.md): Metaprogramação e templates
    - Templates
    - Metaprogramação estática
    - CRTP
- [Capítulo 7](./capitulo7.md): Algoritmos e estruturas de dados
    - Busca
    - Recursão
    - Grafos
- [Capítulo 8](./capitulo8.md): Programação paralela e concorrente
```

**Comment by patrickelectric** [comment]
Acho que seria interessante como algo em ter mente dentro dos tópicos, falar sobre as boas praticas de cada um.
Por exemplo:
- variaveis: Falar sobre a utilização de variáveis com note explicito e inteligível dentro do contexto 
- funções: Bem comportadas e documentadas, organização e etc.

Talvez também seja interessante adicionar um capítulo de ferramentas para projetos ? 
- formatador de código, controle de versão e etc

**Comment by tarcisiofischer** [comment]
Faltou / Não esquecer:

- const, constexpr;
- Memory leaks;
- pimpl
- async, future, promise, thread
- namespaces
- smart pointers
- rvalue, lvalue, &, &&, move, forward... (Move semantics)
- SFINAE
- RAII
- assert, static_assert
- typedef, using
- concepts
